image: python:3.9-slim # You can use a newer version if needed

stages:
  - lint
  - test

before_script:
  - pip install --upgrade pip
  - echo "Contents of requirements.txt before install:" # Debugging aid
  - cat requirements.txt # Debugging aid
  - pip install -r requirements.txt # Install application dependencies
  # Install tools needed for CI jobs directly here
  - pip install flake8 pytest httpx 

flake8_check:
  stage: lint
  script:
    - echo "Running Flake8..."
    - flake8 .
    # Hint: flake8 .
    - # Students to fill this line
  allow_failure: false # The pipeline will fail if Flake8 finds issues

pytest_run:
  stage: test
  script:
    - echo "Running Pytest..."
    - pytest 
    # Hint: pytest tests/ (if tests are in a 'tests' directory) or just 'pytest'
    - # Students to fill this line
  allow_failure: false # The pipeline will fail if any tests fail